import { Box, Flex, Heading, Image, Text } from "@chakra-ui/react";

export default function City(){
    return (
        <>
        <Box
            borderRadius="4px"
            overflow="hidden"
        >
            <Image
                src="/city/london.jpg"
                alt="London"
                h="170px"
                w="100%" />
            <Flex
                p="6"
                align="center"
                justify="space-between"
                border="1px"
                borderColor="yellow.300px"
                borderTop="0"
            >
                <Flex direction="column">
                    <Heading
                        fontSize="xl"
                        fontWeight="500"
                    >
                        Londres
                    </Heading>
                    <Text
                        mt="3xl"
                        fontSize="md"
                        color="gray.500"
                        fontWeight="500"
                    >
                        Reino Unido
                    </Text>
                </Flex>
                <Image
                    src="/flag/uk.svg"
                    alt="" />
            </Flex>
        </Box><Box
            borderRadius="4px"
            overflow="hidden"
        >
                <Image
                    src="/city/paris.jpg"
                    alt="Paris"
                    h="170px"
                    w="100%" />
                <Flex
                    p="6"
                    align="center"
                    justify="space-between"
                    border="1px"
                    borderColor="yellow.300px"
                    borderTop="0"
                >
                    <Flex direction="column">
                        <Heading
                            fontSize="xl"
                            fontWeight="500"
                        >
                            Paris
                        </Heading>
                        <Text
                            mt="3xl"
                            fontSize="md"
                            color="gray.500"
                            fontWeight="500"
                        >
                            França
                        </Text>
                    </Flex>
                    <Image
                        src="/flag/france.svg"
                        alt="" />
                </Flex>
            </Box>
            <Box
            borderRadius="4px"
            overflow="hidden"
        >
            <Image
                src="/city/roma.jpg"
                alt="Roma"
                h="170px"
                w="100%"
            />
            <Flex
                p="6"
                align="center"
                justify="space-between"
                border="1px"
                borderColor="yellow.300px"
                borderTop="0"
            >
                <Flex direction="column">
                    <Heading
                        fontSize="xl"
                        fontWeight="500"
                    >
                        Roma
                    </Heading>
                    <Text
                        mt="3xl"
                        fontSize="md"
                        color="gray.500"
                        fontWeight="500"
                    >
                        Itália
                    </Text>
                </Flex>
                <Image
                    src="/flag/italy.svg"
                    alt=""
                />
            </Flex>
        </Box>
        <Box
            borderRadius="4px"
            overflow="hidden"
        >
            <Image
                src="/city/praga.jpg"
                alt="Praga"
                h="170px"
                w="100%"
            />
            <Flex
                p="6"
                align="center"
                justify="space-between"
                border="1px"
                borderColor="yellow.300px"
                borderTop="0"
            >
                <Flex direction="column">
                    <Heading
                        fontSize="xl"
                        fontWeight="500"
                    >
                        Praga
                    </Heading>
                    <Text
                        mt="3xl"
                        fontSize="md"
                        color="gray.500"
                        fontWeight="500"
                    >
                        Repúbliba Tcheca
                    </Text>
                </Flex>
                <Image
                    src="/flag/czech.svg"
                    alt=""
                />
            </Flex>
        </Box>
        <Box
            borderRadius="4px"
            overflow="hidden"
        >
            <Image
                src="/city/amsterdam.jpg"
                alt="Amsterdam"
                h="170px"
                w="100%"
            />
            <Flex
                p="6"
                align="center"
                justify="space-between"
                border="1px"
                borderColor="yellow.300px"
                borderTop="0"
            >
                <Flex direction="column">
                    <Heading
                        fontSize="xl"
                        fontWeight="500"
                    >
                        Amsterdam
                    </Heading>
                    <Text
                        mt="3xl"
                        fontSize="md"
                        color="gray.500"
                        fontWeight="500"
                    >
                        Holanda
                    </Text>
                </Flex>
                <Image
                    src="/flag/netherlands.svg"
                    alt=""
                />
            </Flex>
        </Box>
        </>
    )
}